### ISSUE TITLE
Add links to related software in README

### ISSUE THREAD

**Issue by dwsilk** [Ylannl/roofer#4]
Hi there!

There is a list of related software at the bottom of the README on this repo, it would be useful to add links to those software if possible (unsure if they are open source as well or not)?

**Comment by Ylannl** [comment]
Hello! thank you for your interest. We have moved this repository to https://github.com/3DBAG/roofer. So you might want to have a look there, I will archive this repository today.

Regarding links in the list of software: [Tyler](https://github.com/3DGI/tyler), [Party walls](https://github.com/tudelft3d/3d-building-metrics), the footprint extractor does not exist at the moment but here is something similar that I know about: https://github.com/Geodan/building-boundary.
